[package]
name = "smallworld-sandbox-old"
description = "Dev/test harness for the smallworld engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[[bin]]
name = "smallworld-old"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
bytemuck.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
env_logger.workspace = true
glam.workspace = true
log.workspace = true
pollster.workspace = true
smallworld-engine.workspace = true
winit.workspace = true
zstd.workspace = true
