[package]
name = "smallworld-sandbox"
description = "Dev/test harness for the smallworld engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[[bin]]
name = "smallworld"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
glam.workspace = true
log.workspace = true
smallworld-engine.workspace = true
winit.workspace = true
